# Generated by Django 5.1.5 on 2025-10-14 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='DJEUGA TCHAKOUA', max_length=100)),
                ('prenom', models.CharField(default='KEVIN', max_length=100)),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
                ('telephone', models.CharField(default='(+237)693104102', max_length=20)),
                ('email', models.EmailField(default='djeugamas@gmail.com', max_length=254)),
                ('linkedin', models.URLField(blank=True, default='linkedin.com/in/kevin-djeuga')),
                ('github', models.URLField(blank=True, default='https://github.com/AMASTAZI')),
                ('objectif', models.TextField(default="Passionné par le digital et l'innovation, je souhaite mettre mes compétences au service de projets technologiques créatifs et impactants.")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('etablissement', models.CharField(max_length=200)),
                ('periode', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='portfolio.profil')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-ordre', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=200)),
                ('entreprise', models.CharField(max_length=200)),
                ('periode', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portfolio.profil')),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['-ordre', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='portfolio.profil')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='portfolio.profil')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
            },
        ),
    ]
