# Generated by Django 5.1.5 on 2025-10-14 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projets/')),
                ('langages', models.CharField(blank=True, help_text='Liste de langages séparés par des virgules', max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='portfolio.profil')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-ordre', '-id'],
            },
        ),
    ]
