# Generated by Django 5.1.5 on 2025-10-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='lien',
            field=models.URLField(blank=True, help_text='Lien vers le projet (ex: démo ou repo)'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
